apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ftgomez/transcribe-front-server:latest
        ports:
        - containerPort: 3001
        volumeMounts:
        - mountPath: /app/data
          name: data-volume
      volumes:
      - name: data-volume
        hostPath:
          path: /app/data

---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 3001  
      targetPort: 3001
  type: NodePort 